version: "4"

services:
  postgres:
    image: postgres:16.0
    container_name: mayhem_database
    environment:
      POSTGRES_DB: "mayhem"
      POSTGRES_USER: "biba"
      POSTGRES_PASSWORD: "boba"
      PGDATA: "/postgresql/data/pgdata"
    volumes:
      - .:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  tg_bot:
    container_name: tg_bot
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    expose:
      - 3000
    ports:
      - "3000:3000"
    command: >
      /bin/sh -c 'python main.py'
